###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: shoplo-lifx-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=lifx
        - MYSQL_DATABASE=php_lifx
        - MYSQL_USER=php
        - MYSQL_PASSWORD=lifx

    webserver:
      image: nginx:alpine
      container_name: shoplo-lifx-webserver
      working_dir: /application
      volumes:
          - ../application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8002:80"

    php-fpm:
      build: application/php
      container_name: shoplo-lifx-php-fpm
      working_dir: /application
      volumes:
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    node-js:
      build: application/js
      working_dir: /application
      container_name: shoplo-lifx-node-js
      ports:
         - "8003:8080"

